# Generated by Django 6.0.5 on 2026-06-02 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Friendly name, e.g. 'Main GitHub Repo'", max_length=200)),
                ('platform_type', models.CharField(choices=[('GITHUB', 'GitHub'), ('JIRA', 'Jira'), ('AWS', 'Aws')], max_length=10)),
                ('secret_token', models.CharField(help_text='Shared secret for webhook verification', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='PULL_REQUEST_OPENED, SERVER_CRASH', max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Raw JSON data from external tool')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='monitor.integration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_resolved', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('activity_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='monitor.activitylog')),
            ],
            options={
                'ordering': ['-activity_log__created_at'],
            },
        ),
    ]
