# Generated by Django 6.0.5 on 2026-06-11 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_activitylog_options_alter_integration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='monitor.integration'),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
