# Generated by Django 6.0.5 on 2026-06-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_activitylog_integration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='platform_type',
            field=models.CharField(choices=[('GITHUB', 'GitHub'), ('JIRA', 'Jira'), ('AWS', 'Aws'), ('SLACK', 'Slack')], max_length=10),
        ),
    ]
