"""
Django settings for devpulse_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta 
from dotenv import load_dotenv
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'fallback-unsafe-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ["*"]    # Allow all hosts (for development only)
CSRF_TRUSTED_ORIGINS = ["https://*.ngrok-free.app"]

# Application definition

INSTALLED_APPS = [
    "daphne",   # Must be FIRST — enables WebSocket server
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',   # Django REST Framework
    'django_filters',   # URL filtering

    'rest_framework_simplejwt.token_blacklist',     #Simple JWT only blacklists refresh tokens
    'monitor'    # Our app
]   

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devpulse_backend.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  #Add this so Django finds our dashboard.html
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
# --- ASGI (needed for WebSockets) ---
ASGI_APPLICATION = "devpulse_backend.asgi.application"

WSGI_APPLICATION = 'devpulse_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',   # Specifies the database engine. In this case, PostgreSQL.
        'NAME': os.getenv('DB_NAME', 'devpulse_db'), # The name of the specific database.
        'USER':os.getenv('DB_USER', 'devpulse_user'),# The database user authorized to access 'devpulse_db'.
        'PASSWORD':os.getenv('DB_PASSWORD', ''),     # The password of database.
        'HOST':os.getenv('DB_HOST', '127.0.0.1'),    # The network address where the database server is running.
        'PORT': os.getenv('DB_PORT', '5432'),        # The port number the database 
    }
}

REST_FRAMEWORK ={
    "DEFAULT_AUTHENTICATION_CLASSES":[
        "monitor.authentication.SafeJWTAuthentication",
    ],
    
    'DEFAULT_PERMISSION_CLASSES': (
        # This keeps your views secure by default
        'rest_framework.permissions.IsAuthenticated',
    ),

    # Automatically paginate large result sets (max 20 items per page)
    "DEFAULT_PAGINATION_CLASS":"rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE":20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME_LATE_USER': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME_LATE_USER': timedelta(days=30),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,  # ← New refresh token on each refresh
    'BLACKLIST_AFTER_ROTATION': True,    # ← Old refresh token auto-blacklisted
}
# --- Redis connection (for WebSockets and Celery) ---
CHANNEL_LAYERS={
    "default":{
        "BACKEND":"channels_redis.core.RedisChannelLayer",
        "CONFIG":{
            "hosts":[("127.0.0.1",6379)],
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"       # Where Celery looks for new tasks
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"   # Where Celery stores task results
CELERY_ACCEPT_CONTENT = ["json"]                       # Only accept JSON-formatted tasks
CELERY_TASK_SERIALIZER = "json"                        # Serialize task arguments as JSON
CELERY_RESULT_SERIALIZER = "json"                      # Serialize task results as JSON
CELERY_TIMEZONE = "UTC"                                # Match our database timezone


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
